// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0osw8Xf6D4pasEB-ah6uet70IxTy6NGc',
    appId: '1:181770400018:web:4db6b640a4e2ad8bd743cb',
    messagingSenderId: '181770400018',
    projectId: 'myprofile-99e39',
    authDomain: 'myprofile-99e39.firebaseapp.com',
    storageBucket: 'myprofile-99e39.appspot.com',
    measurementId: 'G-4996GC0H7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGEhEwE9T_KvUtwgIJGE3nEjSHXRIBoo',
    appId: '1:181770400018:android:fee1a914d5a19c76d743cb',
    messagingSenderId: '181770400018',
    projectId: 'myprofile-99e39',
    storageBucket: 'myprofile-99e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyXKk_GNVNJpvLVQJIgfpPgkCa7F_zmo',
    appId: '1:181770400018:ios:1d98763c66d48812d743cb',
    messagingSenderId: '181770400018',
    projectId: 'myprofile-99e39',
    storageBucket: 'myprofile-99e39.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
